# Generated by Django 3.0.8 on 2020-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappeningInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info', models.TextField(blank=True, verbose_name='Betalningsinformation')),
            ],
            options={
                'verbose_name': 'Evenemangsinformation',
                'verbose_name_plural': 'Evenemangsinformation',
            },
        ),
    ]
