# Generated by Django 3.0.8 on 2020-08-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0003_auto_20200805_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
