# Generated by Django 3.0.8 on 2020-08-05 14:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0004_registration_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='automatic_confirmation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Fadder'), (2, 'nØllan'), (3, 'Senior'), (4, 'Extern'), (5, 'Administrativ')], max_length=9),
        ),
    ]
