# Generated by Django 3.1.12 on 2021-06-28 00:49

from django.db import migrations, models
import multiselectfield.db.fields
import nollesystemet.models.misc


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0005_happening_automatic_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappeningSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info_html', models.TextField(blank=True, verbose_name='Betalningsinformation (HTML)')),
                ('payment_info_plain_text', models.TextField(blank=True, verbose_name='Betalningsinformation (Plain text)')),
                ('payment_info_post_price_html', models.TextField(blank=True, verbose_name='Betalningsinformation efter pris (HTML)')),
                ('payment_info_post_price_plain_text', models.TextField(blank=True, verbose_name='Betalningsinformation efter pris (Plain text)')),
            ],
            options={
                'verbose_name': 'Evenemangsinställningar',
                'verbose_name_plural': 'Evenemangsinställningar',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_warning_banner', models.BooleanField(default=False, verbose_name='Visa varningstext')),
                ('warning_banner_text', models.TextField(blank=True, verbose_name='Varningstext')),
            ],
            options={
                'verbose_name': 'Sidinställningar',
                'verbose_name_plural': 'Sidinställningar',
            },
        ),
        migrations.DeleteModel(
            name='HappeningInfo',
        ),
        migrations.AddField(
            model_name='happening',
            name='include_extra_in_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteparagraphlist',
            name='ascending_order',
            field=models.BooleanField(choices=[(True, 'Stigande'), (False, 'Avtagande')], default=True, verbose_name='Ordning'),
        ),
        migrations.AlterField(
            model_name='drinkoption',
            name='drink',
            field=models.CharField(max_length=30, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='dynamicnolleformquestion',
            name='number_label',
            field=models.CharField(max_length=30, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='dynamicnolleformquestion',
            name='title',
            field=models.CharField(max_length=150, null=None, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='extraoption',
            name='extra_option',
            field=models.CharField(max_length=30, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='contact_email',
            field=models.EmailField(max_length=254, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='contact_name',
            field=models.CharField(max_length=150, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='contact_phone',
            field=models.CharField(max_length=30, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='description',
            field=models.CharField(max_length=500, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='image_file_path',
            field=models.CharField(max_length=50, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='location',
            field=models.CharField(max_length=200, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='happening',
            name='user_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Fadder'), (2, 'nØllan'), (3, 'Senior'), (4, 'Extern'), (5, 'Administrativ')], max_length=9),
        ),
        migrations.AlterField(
            model_name='nollegroup',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji], verbose_name='Namn'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='food_preference',
            field=models.TextField(blank=True, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
    ]
