# Generated by Django 3.2.5 on 2021-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0006_auto_20210710_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fadderiet_footer_left',
            field=models.TextField(blank=True, verbose_name='Footer vänster'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fadderiet_footer_right',
            field=models.TextField(blank=True, verbose_name='Footer höger'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fadderiet_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fadderiets logga'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fohseriet_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Föhseriets logga'),
        ),
    ]
