# Generated by Django 3.2.5 on 2021-07-14 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('nollesystemet', '0008_feedback'), ('nollesystemet', '0009_alter_feedback_timestamp')]

    dependencies = [
        ('nollesystemet', '0007_auto_20210710_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('target', models.PositiveSmallIntegerField(choices=[(1, 'Fysiksektionens mottagning'), (2, 'Mottagningen i allmänhet (Kåren)'), (3, 'nØllesystemet')])),
            ],
            options={
                'verbose_name': 'Feedbackprenumerant',
                'verbose_name_plural': 'Feedbackprenumeranter',
                'unique_together': {('email', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveSmallIntegerField(choices=[(1, 'Fysiksektionens mottagning'), (2, 'Mottagningen i allmänhet (Kåren)'), (3, 'nØllesystemet')])),
                ('anonymous', models.BooleanField(default=False)),
                ('external_name', models.CharField(blank=True, max_length=100, null=True)),
                ('external_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback', models.TextField()),
                ('notified_observers', models.ManyToManyField(editable=False, related_name='received_feedbacks', to='nollesystemet.FeedbackObserver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nollesystemet.userprofile')),
                ('timestamp', models.DateTimeField(auto_created=True, editable=False)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
