# Generated by Django 3.2.5 on 2021-07-29 08:10

from django.db import migrations, models
import nollesystemet.models.misc


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0009_nolleformanswer_special_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicnolleformquestion',
            name='number_label',
            field=models.CharField(max_length=50, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji]),
        ),
    ]
