# Generated by Django 3.2.5 on 2021-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0010_alter_dynamicnolleformquestion_number_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='nollegroup',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
