# Generated by Django 3.2.5 on 2021-08-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0012_auto_20210805_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='OCR',
            field=models.CharField(default='0', editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
