# Generated by Django 3.2.5 on 2021-08-16 21:48

from django.db import migrations, models
import django.db.models.deletion
import nollesystemet.models.misc


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0015_auto_20210815_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSafariGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji])),
                ('responsible_fadders', models.ManyToManyField(limit_choices_to={'user_type__in': [1, 6, 5]}, related_name='campus_safari_group', to='nollesystemet.UserProfile')),
            ],
            options={
                'verbose_name': 'Campus Safari-grupp',
                'verbose_name_plural': 'Campus Safari-grupper',
            },
        ),
        migrations.CreateModel(
            name='CampusSafariSideQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji])),
                ('point', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Campus Safari-sidouppdrag',
                'verbose_name_plural': 'Campus Safari-sidouppdrag',
            },
        ),
        migrations.CreateModel(
            name='CampusSafariStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[nollesystemet.models.misc.validate_no_emoji])),
            ],
            options={
                'verbose_name': 'Campus Safari-station',
                'verbose_name_plural': 'Campus Safari-stationer',
            },
        ),
        migrations.CreateModel(
            name='CampusSafariStationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_points', to='nollesystemet.campussafarigroup')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_points', to='nollesystemet.campussafaristation')),
            ],
        ),
        migrations.AddField(
            model_name='campussafarigroup',
            name='side_quests',
            field=models.ManyToManyField(related_name='successful_groups', to='nollesystemet.CampusSafariSideQuest'),
        ),
    ]
