# Generated by Django 3.2.5 on 2021-08-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0017_auto_20210817_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campussafarigroup',
            name='side_quests',
            field=models.ManyToManyField(blank=True, null=True, related_name='successful_groups', to='nollesystemet.CampusSafariSideQuest'),
        ),
    ]
