# Generated by Django 3.2.5 on 2021-08-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nollesystemet', '0018_alter_campussafarigroup_side_quests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campussafarisidequest',
            old_name='point',
            new_name='points',
        ),
    ]
